# Generated by Django 4.2.30 on 2026-08-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_board_column'),
        ('db', '0127_issuegitlabmeta_projectgitlabconfig'),
    ]

    operations = [
    ]
